# Generated by Django 4.2.4 on 2023-08-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_alter_groupmember_options_alter_reply_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'Group Member', 'verbose_name_plural': 'Group Members'},
        ),
        migrations.AlterModelOptions(
            name='userpost',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
