# Generated by Django 4.2.4 on 2023-08-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_alter_commment_parent_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
