# Generated by Django 4.2.4 on 2023-08-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0006_group_description_alter_group_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='group_joined',
            new_name='parent_group',
        ),
        migrations.AlterField(
            model_name='commment',
            name='date_commented',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
