# Generated by Django 4.2.4 on 2023-08-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_rename_group_joined_groupmember_parent_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='is_admin',
            new_name='is_group_admin',
        ),
    ]
