# Generated by Django 4.2.4 on 2023-08-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0009_rename_parent_group_groupmember_group_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='is_group_admin',
            new_name='is_admin',
        ),
    ]
