# Generated by Django 4.2.4 on 2023-08-26 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_app', '0011_rename_is_admin_groupmember_is_group_admin_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('parent_user', 'follower')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('member', 'parent_group')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liker', 'parent_post')},
        ),
    ]
