# Generated by Django 4.2.4 on 2023-08-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0012_alter_follower_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='viewed',
            new_name='is_viewed',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
