# Generated by Django 4.2.4 on 2023-08-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_profile_image_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media/profile-pics'),
        ),
    ]
